#!/usr/bin/env python3
"""Guided deployment material generator for OpenClaw Nexus.

The wizard intentionally does not deploy anything on its own.  It creates a
reviewable operator bundle with an environment file, a Docker Compose override,
and a bootstrap helper for DB-bound Nexusctl agent tokens.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import secrets
import stat
import sys
import textwrap
from typing import Literal

DeploymentProfile = Literal["development", "internal-production"]
VolumeMode = Literal["named", "host"]

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "deploy" / "wizard"
VOLUME_TARGETS = {
    "nexus_data": "/data",
    "nexus_backups": "/backups",
    "recovery_evidence": "/recovery-evidence",
    "workspaces": "/workspaces",
    "repo_worktrees": "/repo-worktrees",
}


@dataclass(frozen=True, slots=True)
class WizardConfig:
    profile: DeploymentProfile
    output_dir: Path
    api_host: str
    api_port: int
    openclaw_gateway_port: int
    volume_mode: VolumeMode
    host_volume_root: Path | None
    github_mode: str
    webhook_reconciliation: bool
    generate_webhook_secret: bool
    github_webhook_secret: str

    @property
    def env_filename(self) -> str:
        return f".env.{self.profile}"


def generate_secret() -> str:
    """Return a URL-safe operator secret suitable for webhook HMAC use."""

    return secrets.token_urlsafe(48)


def build_env(config: WizardConfig) -> str:
    tls_enabled = "1" if config.profile == "internal-production" else "0"
    insecure_bind = "0" if config.profile == "internal-production" else "1"
    insecure_remote = "0" if config.profile == "internal-production" else "1"
    webhook_reconciliation = "1" if config.webhook_reconciliation else "0"
    secret_note = "generated by deployment_wizard.py" if config.generate_webhook_secret else "provided by operator"

    return textwrap.dedent(
        f"""
        # Generated by scripts/deployment_wizard.py. Review before use.
        # Keep this file out of version control; it may contain secrets.
        NEXUSCTL_DEPLOYMENT_MODE={config.profile}
        NEXUSCTL_API_HOST={config.api_host}
        NEXUSCTL_API_PORT={config.api_port}
        NEXUSCTL_API_TIMEOUT_SECONDS=5
        NEXUSCTL_API_READ_RETRIES=1
        NEXUSCTL_API_MAX_BODY_BYTES=1048576
        NEXUSCTL_API_TLS_ENABLED={tls_enabled}
        NEXUSCTL_API_ALLOW_INSECURE_REMOTE_BIND={insecure_bind}
        NEXUSCTL_API_ALLOW_INSECURE_REMOTE={insecure_remote}

        NEXUSCTL_PROJECT_ROOT=/workspace
        NEXUSCTL_DB=/data/nexus.db
        NEXUSCTL_BACKUP_DIR=/backups
        NEXUSCTL_RECOVERY_EVIDENCE_DIR=/recovery-evidence
        NEXUSCTL_BACKUP_RETENTION_DAYS=30
        NEXUSCTL_BACKUP_RETENTION_MIN_COPIES=7
        NEXUSCTL_OFFSITE_BACKUP_ENABLED=0
        NEXUSCTL_OFFSITE_BACKUP_TARGET=operator-managed-offsite-location
        NEXUSCTL_OFFSITE_BACKUP_SCHEDULE=daily
        NEXUSCTL_WORKSPACES_DIR=/workspaces
        NEXUSCTL_REPO_WORKTREES_DIR=/repo-worktrees
        NEXUSCTL_WORKER_INTERVAL_SECONDS=300
        NEXUSCTL_TOKEN=

        OPENCLAW_GATEWAY_PORT={config.openclaw_gateway_port}
        OPENCLAW_BASE_IMAGE=python:3.11-slim

        NEXUSCTL_GITHUB_MODE={config.github_mode}
        NEXUSCTL_WEBHOOK_RECONCILIATION_ENABLED={webhook_reconciliation}
        # GITHUB_WEBHOOK_SECRET: {secret_note}
        GITHUB_WEBHOOK_SECRET={config.github_webhook_secret}
        GITHUB_APP_ID=
        GITHUB_APP_PRIVATE_KEY_PATH=/run/secrets/github_app_private_key.pem
        GITHUB_APP_INSTALLATION_ID=
        GITHUB_DEFAULT_OWNER=
        GITHUB_DEFAULT_REPO=
        """
    ).strip() + "\n"


def build_compose_override(config: WizardConfig) -> str:
    env_file = config.env_filename
    service_env_files = textwrap.dedent(
        f"""
          nexusctl-api:
            env_file:
              - {env_file}
          nexusctl-worker:
            env_file:
              - {env_file}
          nexusctl-cli:
            env_file:
              - {env_file}
          openclaw-gateway:
            env_file:
              - {env_file}
        """
    ).rstrip()

    if config.volume_mode == "named":
        volume_block = textwrap.dedent(
            """
            volumes:
              nexus-data:
                name: openclaw-nexus-data
              nexus-backups:
                name: openclaw-nexus-backups
              recovery-evidence:
                name: openclaw-nexus-recovery-evidence
              workspaces:
                name: openclaw-nexus-workspaces
              repo-worktrees:
                name: openclaw-nexus-repo-worktrees
            """
        ).rstrip()
        return f"# Generated by scripts/deployment_wizard.py\nservices:\n{service_env_files}\n\n{volume_block}\n"

    root = config.host_volume_root
    if root is None:
        raise ValueError("host_volume_root is required for host volume mode")
    volume_lines = []
    for name, target in VOLUME_TARGETS.items():
        source = (root / name).as_posix()
        volume_lines.append(f"      - {source}:{target}")
    common_volume_block = "\n".join(volume_lines + ["      - ../nexus:/workspace/nexus:ro", "      - ../generated:/workspace/generated"])
    openclaw_volume_block = "\n".join(
        [
            "      - ../generated:/generated:ro",
            f"      - {(root / 'workspaces').as_posix()}:/workspaces",
        ]
    )
    return textwrap.dedent(
        f"""
        # Generated by scripts/deployment_wizard.py
        services:
          nexusctl-api:
            env_file:
              - {env_file}
            volumes:
        {common_volume_block}
          nexusctl-worker:
            env_file:
              - {env_file}
            volumes:
        {common_volume_block}
          nexusctl-cli:
            env_file:
              - {env_file}
            volumes:
        {common_volume_block}
          openclaw-gateway:
            env_file:
              - {env_file}
            volumes:
        {openclaw_volume_block}
        """
    ).strip() + "\n"


def output_ref(config: WizardConfig) -> str:
    try:
        return config.output_dir.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return config.output_dir.as_posix()


def build_bootstrap_script(config: WizardConfig) -> str:
    env_file = config.env_filename
    bundle_dir = output_ref(config)
    return textwrap.dedent(
        f"""
        #!/usr/bin/env sh
        set -eu

        # Run from the project root. This creates DB-bound agent tokens after the
        # SQLite database exists. Do not commit the resulting token output.
        ENV_FILE="{bundle_dir}/{env_file}"
        COMPOSE_OVERRIDE="{bundle_dir}/docker-compose.override.yml"

        docker compose --env-file "$ENV_FILE" -f config/docker-compose.yml -f "$COMPOSE_OVERRIDE" run --rm nexusctl-cli db init --json
        docker compose --env-file "$ENV_FILE" -f config/docker-compose.yml -f "$COMPOSE_OVERRIDE" run --rm nexusctl-cli auth login --agent operator --json

        echo "Copy the emitted credential.token into NEXUSCTL_TOKEN in $ENV_FILE or your secret manager."
        echo "Afterwards run: docker compose --env-file $ENV_FILE -f config/docker-compose.yml -f $COMPOSE_OVERRIDE run --rm nexusctl-cli doctor --json"
        """
    ).strip() + "\n"


def build_readme(config: WizardConfig) -> str:
    bundle_dir = output_ref(config)
    volume_text = (
        "Docker Named Volumes mit stabilen Namen `openclaw-nexus-*`."
        if config.volume_mode == "named"
        else f"Host-Bind-Mounts unter `{config.host_volume_root}`."
    )
    return textwrap.dedent(
        f"""
        # OpenClaw Nexus Deployment Bundle

        Dieses Bundle wurde durch `scripts/deployment_wizard.py` erzeugt und ist ein reviewbarer Startpunkt für ein leichtes Deployment.

        ## Enthaltene Dateien

        - `{config.env_filename}`: Umgebungskonfiguration für `{config.profile}` inklusive generiertem `GITHUB_WEBHOOK_SECRET`, sofern kein Secret übergeben wurde, sowie Review-Werten für Recovery-Evidence, Retention und operator-managed Offsite-Backups.
        - `docker-compose.override.yml`: Compose-Override mit Environment-Datei und Volume-Strategie.
        - `bootstrap-operator-token.sh`: erzeugt nach `db init` einen gültigen DB-gebundenen Operator-Token über `nexusctl auth login`.

        ## Gewählte Volume-Strategie

        {volume_text}

        Persistiert werden Datenbank, Backups, Recovery-Evidence-Manifeste, Workspaces und Repo-Worktrees. `nexus/` wird read-only gemountet; `generated/` wird von OpenClaw read-only konsumiert.

        ## Nutzung

        ```bash
        docker compose --env-file {bundle_dir}/{config.env_filename} -f config/docker-compose.yml -f {bundle_dir}/docker-compose.override.yml build
        sh {bundle_dir}/bootstrap-operator-token.sh
        docker compose --env-file {bundle_dir}/{config.env_filename} -f config/docker-compose.yml -f {bundle_dir}/docker-compose.override.yml up -d
        docker compose --env-file {bundle_dir}/{config.env_filename} -f config/docker-compose.yml -f {bundle_dir}/docker-compose.override.yml run --rm nexusctl-cli doctor --json
        docker compose --env-file {bundle_dir}/{config.env_filename} -f config/docker-compose.yml -f {bundle_dir}/docker-compose.override.yml run --rm nexusctl-cli db restore-drill --json --evidence-path "$NEXUSCTL_RECOVERY_EVIDENCE_DIR/restore-drill-evidence.json"
        ```

        ## Internal-Production-Preflight

        Vor einem Cutover muss das Bundle als Betreiber-Preflight gelesen werden: interne Produktions-Env laden, Datenbank mit `nexusctl db init --json` initialisieren oder migrieren, `nexusctl doctor --json` ausführen, danach `nexusctl db restore-drill --json --evidence-path "$NEXUSCTL_RECOVERY_EVIDENCE_DIR/restore-drill-evidence.json"` erzeugen und das Manifest zusammen mit Retention-, Offsite-, TLS-/Proxy-, Secret-Management- und Monitoring-Nachweisen archivieren. `doctor --json` enthält dafür den maschinenlesbaren Abschnitt `internal_production_preflight`; ein Cutover ist blockiert, solange dort `status_code=blocked` oder Einträge unter `cutover_blockers` erscheinen.

        ## Recovery Evidence Pack

        Für `internal-production` müssen Betreiber die erzeugten Evidence-Manifeste aus `NEXUSCTL_RECOVERY_EVIDENCE_DIR` regelmäßig prüfen, Offsite kopieren und entsprechend ihrer Retention-Policy aufbewahren. `NEXUSCTL_OFFSITE_BACKUP_TARGET` ist nur operator-managed Metadaten und kein Cloud-Secret; echte Provider-Konfiguration gehört außerhalb dieses Bundles ins Secret Management. Grün ist der Betrieb erst, wenn `doctor --json` keine kritischen `operational_readiness`-Einträge für Recovery-Evidence, Retention oder Offsite-Backup-Control meldet und der Restore-Drill ein grünes Manifest liefert.

        ## Grenzen

        Der Wizard generiert nur Secrets, die offline sicher erzeugbar sind. GitHub-App-Private-Keys, produktive Agent-Tokens und echte Offsite-Provider-Credentials gehören in Secret Management. Agent-Tokens werden erst nach Datenbankinitialisierung über Nexusctl erstellt, damit sie zur Token Registry passen. Das Bundle erzwingt keine WORM-, Cloud- oder externe Backup-Infrastruktur.
        """
    ).strip() + "\n"


def write_bundle(config: WizardConfig) -> dict[str, Path]:
    config.output_dir.mkdir(parents=True, exist_ok=True)
    if config.volume_mode == "host" and config.host_volume_root is not None:
        for name in VOLUME_TARGETS:
            (config.host_volume_root / name).mkdir(parents=True, exist_ok=True)

    env_path = config.output_dir / config.env_filename
    compose_path = config.output_dir / "docker-compose.override.yml"
    bootstrap_path = config.output_dir / "bootstrap-operator-token.sh"
    readme_path = config.output_dir / "README.md"
    gitignore_path = config.output_dir / ".gitignore"

    env_path.write_text(build_env(config), encoding="utf-8")
    compose_path.write_text(build_compose_override(config), encoding="utf-8")
    bootstrap_path.write_text(build_bootstrap_script(config), encoding="utf-8")
    readme_path.write_text(build_readme(config), encoding="utf-8")
    gitignore_path.write_text(".env.*\n*.pem\n*.key\n", encoding="utf-8")

    bootstrap_path.chmod(bootstrap_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    return {
        "env": env_path,
        "compose_override": compose_path,
        "bootstrap": bootstrap_path,
        "readme": readme_path,
        "gitignore": gitignore_path,
    }


def ask(prompt: str, default: str) -> str:
    value = input(f"{prompt} [{default}]: ").strip()
    return value or default


def interactive_config(args: argparse.Namespace) -> WizardConfig:
    profile = ask("Deployment-Profil (development/internal-production)", args.profile)
    if profile not in {"development", "internal-production"}:
        raise SystemExit(f"unsupported profile: {profile}")
    volume_mode = ask("Volume-Modus (named/host)", args.volume_mode)
    if volume_mode not in {"named", "host"}:
        raise SystemExit(f"unsupported volume mode: {volume_mode}")
    host_root = None
    if volume_mode == "host":
        host_root = Path(ask("Host-Verzeichnis für persistente Volumes", str(args.host_volume_root))).expanduser()
    github_mode = ask("GitHub-Modus (mock/app)", args.github_mode)
    reconciliation_default = "1" if profile == "internal-production" else "0"
    reconciliation = ask("Webhook-Reconciliation aktivieren (0/1)", reconciliation_default) == "1"
    secret = args.github_webhook_secret or generate_secret()
    return WizardConfig(
        profile=profile,  # type: ignore[arg-type]
        output_dir=args.output_dir,
        api_host=ask("API-Host", "0.0.0.0" if profile == "development" else "127.0.0.1"),
        api_port=int(ask("API-Port", str(args.api_port))),
        openclaw_gateway_port=int(ask("OpenClaw-Gateway-Port", str(args.openclaw_gateway_port))),
        volume_mode=volume_mode,  # type: ignore[arg-type]
        host_volume_root=host_root,
        github_mode=github_mode,
        webhook_reconciliation=reconciliation,
        generate_webhook_secret=not bool(args.github_webhook_secret),
        github_webhook_secret=secret,
    )


def config_from_args(args: argparse.Namespace) -> WizardConfig:
    profile: DeploymentProfile = args.profile
    volume_mode: VolumeMode = args.volume_mode
    host_root = args.host_volume_root if volume_mode == "host" else None
    secret = args.github_webhook_secret or generate_secret()
    return WizardConfig(
        profile=profile,
        output_dir=args.output_dir,
        api_host=args.api_host or ("0.0.0.0" if profile == "development" else "127.0.0.1"),
        api_port=args.api_port,
        openclaw_gateway_port=args.openclaw_gateway_port,
        volume_mode=volume_mode,
        host_volume_root=host_root,
        github_mode=args.github_mode,
        webhook_reconciliation=args.webhook_reconciliation if args.webhook_reconciliation is not None else profile == "internal-production",
        generate_webhook_secret=not bool(args.github_webhook_secret),
        github_webhook_secret=secret,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate a guided OpenClaw Nexus deployment bundle.")
    parser.add_argument("--non-interactive", action="store_true", help="use arguments/defaults without prompting")
    parser.add_argument("--profile", choices=["development", "internal-production"], default="development")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--api-host", default=None)
    parser.add_argument("--api-port", type=int, default=8080)
    parser.add_argument("--openclaw-gateway-port", type=int, default=8090)
    parser.add_argument("--volume-mode", choices=["named", "host"], default="named")
    parser.add_argument("--host-volume-root", type=Path, default=ROOT / ".local" / "volumes")
    parser.add_argument("--github-mode", choices=["mock", "app"], default="mock")
    parser.add_argument("--webhook-reconciliation", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("--github-webhook-secret", default=None, help="provide an existing webhook secret instead of generating one")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = config_from_args(args) if args.non_interactive else interactive_config(args)
    written = write_bundle(config)
    print("Generated deployment bundle:")
    for label, path in written.items():
        print(f"- {label}: {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
    print("Next: review the files, run the bootstrap script, then start Docker Compose with the generated override.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
