"""OpenClaw runtime configuration writer for generated artifacts.

OpenClaw generation makes generated runtime files deterministic and self-verifying.  JSON
files carry an embedded checksum over their canonical payload, while markdown
files use a generated header with a checksum over the body.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from hashlib import sha256
import json
from pathlib import Path
from typing import Any, Iterable, Mapping

from nexusctl.domain.errors import ValidationError

GENERATED_BY = "nexusctl"
CHECKSUM_PREFIX = "sha256:"
MARKDOWN_HEADER_PREFIX = "<!-- @generated by nexusctl; checksum: "
MARKDOWN_HEADER_SUFFIX = "; source: nexus/*.yml; do not edit manually. -->\n\n"


def canonical_json(value: Any) -> str:
    """Return deterministic JSON text used for checksum calculation."""

    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def pretty_json(value: Any) -> str:
    """Return stable pretty JSON with trailing newline for generated files."""

    return json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def checksum_text(text: str) -> str:
    return CHECKSUM_PREFIX + sha256(text.encode("utf-8")).hexdigest()


def checksum_json_payload(payload: Mapping[str, Any]) -> str:
    return checksum_text(canonical_json(payload))


def with_markdown_header(body: str) -> str:
    if not body.endswith("\n"):
        body += "\n"
    checksum = checksum_text(body)
    return f"{MARKDOWN_HEADER_PREFIX}{checksum}{MARKDOWN_HEADER_SUFFIX}{body}"


def managed_json_document(payload: Mapping[str, Any], *, artifact_kind: str) -> dict[str, Any]:
    """Return a JSON object with checksum metadata over the non-metadata payload."""

    body = dict(payload)
    metadata = {
        "artifact_kind": artifact_kind,
        "generated_by": GENERATED_BY,
        "source": "nexus/*.yml",
        "checksum": checksum_json_payload(body),
    }
    return {"_generated": metadata, **body}


@dataclass(frozen=True, slots=True)
class WriteResult:
    path: str
    checksum: str
    changed: bool


@dataclass(frozen=True, slots=True)
class DriftResult:
    path: str
    status: str
    expected_checksum: str | None = None
    actual_checksum: str | None = None
    reason: str | None = None


class ManagedArtifactWriter:
    """Shared write and drift-check helpers for generated artifacts."""

    def __init__(self, project_root: str | Path) -> None:
        self.project_root = Path(project_root)

    def write_text(self, rel_path: str, content: str) -> WriteResult:
        path = self.project_root / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        changed = not path.exists() or path.read_text(encoding="utf-8") != content
        if changed:
            path.write_text(content, encoding="utf-8")
        return WriteResult(path=rel_path, checksum=content_checksum(content), changed=changed)

    def write_markdown(self, rel_path: str, body: str) -> WriteResult:
        content = with_markdown_header(body)
        return self.write_text(rel_path, content)

    def write_json(self, rel_path: str, payload: Mapping[str, Any], *, artifact_kind: str) -> WriteResult:
        document = managed_json_document(payload, artifact_kind=artifact_kind)
        content = pretty_json(document)
        return self.write_text(rel_path, content)

    def ensure_directory(self, rel_path: str) -> None:
        (self.project_root / rel_path).mkdir(parents=True, exist_ok=True)

    def check_markdown(self, rel_path: str) -> DriftResult:
        path = self.project_root / rel_path
        if not path.exists():
            return DriftResult(path=rel_path, status="missing", reason="file is missing")
        text = path.read_text(encoding="utf-8")
        header, separator, body = text.partition("\n\n")
        if not separator or not header.startswith(MARKDOWN_HEADER_PREFIX):
            return DriftResult(path=rel_path, status="unmanaged", reason="missing generated checksum header")
        expected = header.removeprefix(MARKDOWN_HEADER_PREFIX).split(";", 1)[0].strip()
        actual = checksum_text(body)
        return DriftResult(
            path=rel_path,
            status="ok" if expected == actual else "drift",
            expected_checksum=expected,
            actual_checksum=actual,
            reason=None if expected == actual else "body checksum differs from generated header",
        )

    def check_json(self, rel_path: str) -> DriftResult:
        path = self.project_root / rel_path
        if not path.exists():
            return DriftResult(path=rel_path, status="missing", reason="file is missing")
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            return DriftResult(path=rel_path, status="invalid", reason=f"invalid JSON: {exc}")
        if not isinstance(document, dict):
            return DriftResult(path=rel_path, status="invalid", reason="top-level JSON must be an object")
        metadata = document.get("_generated")
        if not isinstance(metadata, dict):
            return DriftResult(path=rel_path, status="unmanaged", reason="missing _generated metadata")
        expected = metadata.get("checksum")
        if not isinstance(expected, str) or not expected.startswith(CHECKSUM_PREFIX):
            return DriftResult(path=rel_path, status="unmanaged", reason="missing generated checksum")
        body = {key: value for key, value in document.items() if key != "_generated"}
        actual = checksum_json_payload(body)
        return DriftResult(
            path=rel_path,
            status="ok" if expected == actual else "drift",
            expected_checksum=expected,
            actual_checksum=actual,
            reason=None if expected == actual else "JSON payload checksum differs from generated metadata",
        )


def content_checksum(content: str) -> str:
    """Checksum over the exact file content for command output."""

    return checksum_text(content)


class OpenClawConfigWriter:
    """Render ``generated/openclaw/openclaw.json`` from Nexus design data."""

    def __init__(self, project_root: str | Path) -> None:
        self.project_root = Path(project_root)
        self.writer = ManagedArtifactWriter(project_root)

    def render_payload(
        self,
        *,
        agents: Iterable[Mapping[str, Any]],
        schedules: Iterable[Mapping[str, Any]],
        guardrails: Mapping[str, Any],
    ) -> dict[str, Any]:
        rendered_agents: list[dict[str, Any]] = []
        for agent in sorted(agents, key=lambda item: str(item.get("id", ""))):
            agent_id = str(agent["id"])
            rendered_agents.append(
                {
                    "id": agent_id,
                    "displayName": agent.get("display_name", agent_id),
                    "domain": agent.get("domain"),
                    "role": agent.get("role"),
                    "agentDir": f"generated/agents/{agent_id}",
                    "workspace": f"generated/workspaces/{agent_id}",
                    "skills": sorted(agent.get("skills") or []),
                    "capabilities": sorted(agent.get("capabilities") or []),
                    "toolPolicy": {
                        "githubDirectWrite": bool((agent.get("github") or {}).get("direct_write", True)),
                        "repoDirectApply": bool((agent.get("repo") or {}).get("direct_apply", True)),
                        "capabilitySource": "nexus/agents.yml",
                        "domainSource": "auth_token",
                    },
                }
            )
            self.writer.ensure_directory(f"generated/workspaces/{agent_id}")

        return {
            "schema_version": 1,
            "runtime": {
                "name": "openclaw",
                "generated": True,
                "source_of_truth": "nexusctl",
                "configuration_source": "nexus/*.yml via nexusctl generation",
                "lifecycle_authority": False,
            },
            "guardrails": {
                "github_is_projection": True,
                "agents_have_direct_github_write_tokens": False,
                "generated_artifacts_are_manual_source_of_truth": False,
                "generated_runtime_config_mutation": "nexusctl_generation_only",
                "runtime_cronjob_mutation": "nexusctl_schedule_control_flow_only",
                "agents_may_edit_generated_runtime_config_directly": False,
                "agents_may_edit_runtime_cronjobs_directly": False,
                **dict(guardrails),
            },
            "agents": rendered_agents,
            "schedules": [
                {
                    "id": item.get("id"),
                    "agent": item.get("agent"),
                    "domain": item.get("domain"),
                    "enabled": bool(item.get("enabled", True)),
                    "cron": str(item.get("cron") or ""),
                    "standing_order": item.get("standing_order"),
                    "cronArtifact": f"generated/openclaw/schedules/{item.get('id')}.json",
                    "mutationBoundary": "nexusctl_schedule_control_flow_only",
                }
                for item in sorted(schedules, key=lambda sched: str(sched.get("id", "")))
            ],
        }

    def write(
        self,
        *,
        agents: Iterable[Mapping[str, Any]],
        schedules: Iterable[Mapping[str, Any]],
        guardrails: Mapping[str, Any],
    ) -> WriteResult:
        payload = self.render_payload(agents=agents, schedules=schedules, guardrails=guardrails)
        return self.writer.write_json("generated/openclaw/openclaw.json", payload, artifact_kind="openclaw_config")

    def expected_paths(self) -> tuple[str, ...]:
        return ("generated/openclaw/openclaw.json",)

    def check(self) -> list[DriftResult]:
        return [self.writer.check_json(path) for path in self.expected_paths()]
