from __future__ import annotations

from typing import Any


def _list_block(values: list[str] | None) -> str:
    if not values:
        return "- none"
    return "\n".join(f"- {item}" for item in values)


def render_issue_body(*, request: dict[str, Any], repo: dict[str, Any], implementation_context: dict[str, Any]) -> str:
    task = request.get("sanitized_summary") or request.get("objective") or request.get("task") or request["request_id"]
    component = implementation_context.get("component") or "unspecified"
    acceptance = implementation_context.get("acceptance_criteria") or request.get("acceptance_criteria") or []
    return f"""# {task}

Nexus Request: {request['request_id']}

## Task
{request.get('sanitized_summary') or task}

## Target
- Repo: {repo['repo_id']}
- Branch: {request.get('branch')}
- Component: {component}

## Implementation Context

### Entrypoints
{_list_block(implementation_context.get('entrypoints'))}

### Likely Files
{_list_block(implementation_context.get('likely_files'))}

### Do Not Touch
{_list_block(implementation_context.get('do_not_touch'))}

## Acceptance Criteria
{_list_block(acceptance)}

## Test Commands
{_list_block(implementation_context.get('test_commands'))}

---
Generated by Nexus. Nexus is the source of truth for lifecycle, assignment and evidence.
""".strip() + "\n"
