from __future__ import annotations

from contextlib import redirect_stderr, redirect_stdout
from dataclasses import dataclass
from io import StringIO
import json
import os
from pathlib import Path
import sys

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "nexusctl" / "src"))

from nexusctl.interfaces.cli.main import main as cli_main


pytestmark = [pytest.mark.integration, pytest.mark.slow]


@dataclass(frozen=True)
class CliResult:
    returncode: int
    stdout: str
    stderr: str


def run_cli(args: list[str], *, env: dict[str, str] | None = None) -> CliResult:
    old_env = os.environ.copy()
    os.environ.update(env or {})
    stdout = StringIO()
    stderr = StringIO()
    try:
        with redirect_stdout(stdout), redirect_stderr(stderr):
            returncode = cli_main(args)
    finally:
        os.environ.clear()
        os.environ.update(old_env)
    return CliResult(returncode=returncode, stdout=stdout.getvalue(), stderr=stderr.getvalue())



def login(db: Path, project: Path, agent: str) -> str:
    result = run_cli([
        "auth", "login", "--agent", agent,
        "--db", str(db), "--project-root", str(project), "--json",
    ])
    assert result.returncode == 0, result.stderr or result.stdout
    return json.loads(result.stdout)["credential"]["token"]


def test_openclaw_generation_generates_openclaw_agents_skills_and_detects_drift(tmp_path: Path, repo_project_copy: Path) -> None:
    project = repo_project_copy
    db = tmp_path / "nexus.db"
    token = login(db, project, "platform-maintainer")

    generated = run_cli([
        "generate", "all", "--db", str(db), "--project-root", str(project), "--json",
    ], env={"NEXUSCTL_TOKEN": token})
    assert generated.returncode == 0, generated.stderr or generated.stdout
    payload = json.loads(generated.stdout)
    assert payload["ok"] is True
    assert payload["kind"] == "all"
    assert payload["artifact_count"] >= 120
    artifact_paths = {item["path"] for item in payload["artifacts"]}
    assert "generated/openclaw/openclaw.json" in artifact_paths
    assert "generated/agents/software-builder/TOOLS.md" in artifact_paths
    assert "generated/skills/allowlists/software-builder.json" in artifact_paths
    assert "generated/skills/tool-policies/software-builder.json" in artifact_paths

    openclaw = json.loads((project / "generated/openclaw/openclaw.json").read_text())
    agents = {agent["id"]: agent for agent in openclaw["agents"]}
    assert agents["software-builder"]["agentDir"] == "generated/agents/software-builder"
    assert agents["software-builder"]["workspace"] == "generated/workspaces/software-builder"
    assert agents["software-builder"]["toolPolicy"]["githubDirectWrite"] is False
    assert agents["software-builder"]["toolPolicy"]["repoDirectApply"] is False

    tools_md = project / "generated/agents/software-builder/TOOLS.md"
    text = tools_md.read_text(encoding="utf-8")
    assert text.startswith("<!-- @generated by nexusctl; checksum: sha256:")
    assert "`nexusctl_patch_proposal`" in text
    assert "`patch.submit`" in text

    allowlist = json.loads((project / "generated/skills/allowlists/software-builder.json").read_text())
    assert allowlist["skills"] == ["nexusctl_feature_request_ops", "nexusctl_patch_proposal"]

    doctor = run_cli(["doctor", "--project-root", str(project), "--db", str(db), "--json"])
    assert doctor.returncode == 0, doctor.stdout
    assert json.loads(doctor.stdout)["drift_count"] == 0

    tools_md.write_text(tools_md.read_text(encoding="utf-8") + "\nmanual drift\n", encoding="utf-8")
    drifted = run_cli(["doctor", "--project-root", str(project), "--db", str(db), "--json"])
    assert drifted.returncode == 1
    drift_payload = json.loads(drifted.stdout)
    assert drift_payload["ok"] is False
    assert any(item["path"] == "generated/agents/software-builder/TOOLS.md" for item in drift_payload["drift"])


def test_openclaw_generation_generation_requires_runtime_generate_capability(tmp_path: Path, repo_project_copy: Path) -> None:
    project = repo_project_copy
    db = tmp_path / "nexus.db"
    builder_token = login(db, project, "software-builder")

    denied = run_cli([
        "generate", "agents", "--db", str(db), "--project-root", str(project), "--json",
    ], env={"NEXUSCTL_TOKEN": builder_token})
    assert denied.returncode == 3
    payload = json.loads(denied.stdout)
    assert payload["ok"] is False
    assert payload["rule_id"] == "capability_not_granted"
